app/models/accessory.rb
app/models/psychic.rb
db/migrate/20201116155713_create_psychics.rb
db/migrate/20201116160516_create_accessories.rb
test/models/accessory_test.rb
test/models/psychic_test.rb

Adding psychic and accessory models to the application.

add psychic and accessory models

---

app/models/booking.rb
db/migrate/20201116154823_create_bookings.rb
test/models/booking_test.rb

création du modèle booking à revoir ensemble

created booking model

---

app/controllers/bookings_controller.rb
test/controllers/bookings_controller_test.rb

j'ai juste rajouté le squellette du controller booking avec les méthodes qu'on va devoir faire pour notre premier user journey

rajout du controller bookings et des méthodes vides dedans

---

app/controllers/bookings_controller.rb
config/routes.rb

Tristant --> j'ai corrigé tes routes car ça ne fonctionnait pas (j'avais une erreur), il manquait des trucs, je te laisse revoir
j'ai rajouté les routes pour bookings (j'ai modifié aussi en rouge sur le google sheet) et ça me fait un truc chelou car j'ai pour l'action "update" à la fois un put et un patch.
j'ai vu ça: https://stackoverflow.com/questions/47347250/update-action-of-a-restful-route-in-rails-patch-or-put
qui a l'air de dire que pas trop grave mais j'ai un doute...
Faisons un ticket pour ce sujet et aussi le sujet avec le nesting user/psychics

fait les routes avec booking, corrigé routes psychics

---

config/routes.rb

finalement pas le seed mais le routes de index/show pour psychis

changed the route for psychics index and show

---

app/controllers/bookings_controller.rb

changment inutile

---

Gemfile
Gemfile.lock
app/models/accessory.rb
config/routes.rb
db/migrate/20201117152115_change_column_accessories.rb
db/schema.rb
db/seeds.rb

il faudra d'ailleurs changer la relation entre psychic et accessories en mettant une table de jointure

seed avec les dépendances sur les autres fichiers

---

app/controllers/application_controller.rb
app/models/user.rb
app/views/devise/registrations/new.html.erb

- name + last_name in the device sign up form
- validations in User model
- permissions in application controller

added name lastname to user model, form  and validations

---

app/assets/stylesheets/components/_card.scss
app/controllers/psychics_controller.rb
app/views/psychics/index.html.erb
app/views/shared/_navbar.html.erb

- added @psychics to index method in controller
- added link to root on navbar crystal ball
- cards on index page
To be modified : 
- price on cards (error in positionning)
- navbar overlap via body padding
- when the h2 is visible (no overlap), style and center it

psychics index to be modified

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/controllers/psychics_controller.rb
app/views/psychics/show.html.erb

- fait la vew de psychic
- bonne galère avec le bouton pour le mettre en haut à droite de la flexbox mais j'ai trouvé une bonne méthode si vous voulez que je vous explique à l'occaz
- j'ai modifié aussi les feuille de style du coup
- il faudra faire la route et la view de booking pour que le bouton "book now" fonctionne of course, ne pas oublier !

fait la show de psychic

---

db/seeds.rb

reparation seed après migrattion booking

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/psychics/_index.scss
app/assets/stylesheets/psychics/_psychic.scss
app/assets/stylesheets/psychics/_psychics.scss
app/views/psychics/index.html.erb
app/views/psychics/show.html.erb

small modifications (background, image in show)

front modifications of index and show

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

j'ai retouché la HP en mettant des containers pour le texte, en faisant le texte et en mettant des gifs (que je dois aligner dans la page maintenant)

pimped la hp

---

.gitignore
Gemfile
Gemfile.lock
app/controllers/psychics_controller.rb
app/models/psychic.rb
app/views/psychics/edit.html.erb
app/views/psychics/index.html.erb
app/views/psychics/new.html.erb
app/views/psychics/show.html.erb
config/environments/development.rb
config/environments/production.rb
config/routes.rb
config/storage.yml
db/migrate/20201119093936_create_active_storage_tables.active_storage.rb
db/schema.rb

Front a fond

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

- linear purple bg
- infos + gifs in responsive sections
- purple icons on footer

purple bg, info cards gifs re organized, footer icons color

---

app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/psychics/_psychic.scss
app/views/bookings/new.html.erb
app/views/pages/home.html.erb
app/views/psychics/show.html.erb

- linear bckg
- go back btn
- small modifs in hp

front modifs in hp, show

---

app/assets/stylesheets/components/_card.scss
app/views/psychics/index.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb
db/seeds.rb

modifs:
- quelques trucs mineurs dans la view index
- footer modifs
- boutons dans la nav bar qui changent en fonction du log ou pas et du profil avec  un psychic ou pas
- modif de la seed plus propre et avec des vraies addresses

modif nav foot et index

---

app/assets/stylesheets/components/_card.scss
app/views/psychics/index.html.erb

réglé le pb du prix j'espere

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/psychics/_edit.scss
app/assets/stylesheets/psychics/_index.scss
app/assets/stylesheets/psychics/_new.scss
app/models/accessory.rb
app/models/psychic.rb
app/views/psychics/edit.html.erb
app/views/psychics/index.html.erb
app/views/psychics/new.html.erb
app/views/psychics/show.html.erb
app/views/shared/_navbar.html.erb
db/seeds.rb

- myprofile on nav
-deleted home mon nav (already on crystal ball)
- front edit psychic
- front add psychic
- more specialties on seed and in forms
- more accessories on seed
TO DO : add accessories in forms

lots of front modifs

---

app/assets/stylesheets/components/_card.scss
app/views/psychics/index.html.erb
db/seeds.rb

je vous ai fait un joli seed
+ je pense avoir réglé les pb d'image sur l'index jespère

changed seed and image display

---

Gemfile
Gemfile.lock
app/controllers/psychics_controller.rb
app/models/psychic.rb
app/views/psychics/index.html.erb

j'ai créé un search simple sur user name et psychic localisation et spécialité
je  vais rajouter sur les accessoires mais je sais pas pourquoi ça merde un peu

premiere version du search

---

app/controllers/psychics_controller.rb
app/models/psychic.rb

résolu pour search accessories

done multisearch sur accessories

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_search.scss
app/models/psychic.rb
app/views/psychics/index.html.erb

- relooké la search bar dans index
- rajouté le search sur last name de user

search bar relookee et petite modif sur le search pour inclure last name
